# Generated by Django 4.0 on 2021-12-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spell',
            new_name='Comment',
        ),
    ]
